server:
    port: 8083

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/auth
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: update
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8083/auth/realms/restaurant

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
