version: '3.8'

services:
  config-service:
    image: your_docker_image_for_config_service
    ports:
      - "8888:8888"
    networks:
      - app-network

  discovery-service:
    image: your_docker_image_for_discovery_service
    ports:
      - "8761:8761"
    networks:
      - app-network

  gateway-service:
    image: your_docker_image_for_gateway_service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - discovery-service

  auth-service:
    image: your_docker_image_for_auth_service
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - discovery-service

  order-service:
    image: your_docker_image_for_order_service
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - discovery-service
      - kafka
      - redis

  menu-service:
    image: your_docker_image_for_menu_service
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - discovery-service

  notification-service:
    image: your_docker_image_for_notification_service
    ports:
      - "8084:8084"
    networks:
      - app-network
    depends_on:
      - kafka

  inventory-service:
    image: your_docker_image_for_inventory_service
    ports:
      - "8085:8085"
    networks:
      - app-network
    depends_on:
      - kafka
      - redis

  delivery-service:
    image: your_docker_image_for_delivery_service
    ports:
      - "8086:8086"
    networks:
      - app-network

  customer-service:
    image: your_docker_image_for_customer_service
    ports:
      - "8087:8087"
    networks:
      - app-network
    depends_on:
      - kafka

  review-service:
    image: your_docker_image_for_review_service
    ports:
      - "8088:8088"
    networks:
      - app-network
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch

networks:
  app-network:
    driver: bridge
