server:
    port: 8085

spring:
    data:
        elasticsearch:
            client:
                reactive:
                    endpoints: localhost:9200
    kafka:
        bootstrap-servers: localhost:9092

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
