server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/orders
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: update

kafka:
    bootstrap-servers: localhost:9092
    topic: orders

    zipkin:
        base-url: http://zipkin-server:9411 # URL адрес сервера Zipkin

management:
  endpoints:
    web:
      exposure:
          include: health,info,metrics
  endpoint:
    health:
        show-details: always